title: Congzheng Liu 刘丛峥
logo: /assets/img/logo.jpg
email: s43cliu at uni-bonn dot de
description: 
favicon: true
color-scheme: auto
  

navigation:
  - name: Home
    link: ./home.html

  - name: Notes
    link: ./notes.html

  - name: More
    link: ./more.html



