title: Congzheng Liu 刘丛峥
logo: /assets/img/logo.jpg
email: person@address.com
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  

navigation:
  - name: Readme
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: About me
    link: ./about-me.html
