title: Congzheng Liu 刘丛峥
logo: /assets/img/logo.jpg
email: s43cliu at uni-bonn dot de
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  

navigation:
  - name: About me
    link: ./aboutme.html

  - name: Notes
    link: ./notes.html
