remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme
color-scheme: auto
platforms: false
favicon: true

title: Congzheng Liu 刘丛峥
email: s43cliu at uni-bonn dot de


  

navigation:
  - name: Home
    link: ./home.html

  - name: Notes
    link: ./notes.html

  - name: More
    link: ./more.html



