title: Congzheng Liu 刘丛峥
logo: /assets/img/logo.jpg
email: s43cliu at uni-bonn dot de
description: 
favicon: true
color-scheme: auto
  

navigation:
  - name: About me
    link: ./aboutme.html

  - name: Notes
    link: ./notes.html

  - name: Funny
    link: ./funny.html



